version: "3"
services:
  mre:
    volumes:
      - screenshots:/screenshots
    ports:
      - "3901:3901"
    build:
      context: .
    environment:
      STEL_URL: http://stellarium:8090/
      STEL_OUTDIR: /screenshots/
    networks:
      - internal
    depends_on:
      - "stellarium"
  stellarium:
    build:
      context: ./skybox-stellarium/
      dockerfile: "./Dockerfile"
    networks:
      - internal
    volumes:
      - screenshots:/root/screenshots
  nginx:
    image: nginx:alpine
    volumes:
      - screenshots:/usr/share/nginx/html
    ports:
      - "80:80"
volumes:
  screenshots:
networks:
  internal: