version: "3"
services:
  mre:
    volumes:
      - screenshots:/screenshots
    ports:
      - "3901:3901"
    build:
      context: ./skybox-mre/
    environment:
      STEL_URL: http://stellarium:8090
      STEL_OUTDIR: /screenshots/
    networks:
      - internal
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        compress: "true"
    depends_on:
      - "stellarium"
  stellarium:
    build:
      context: ./skybox-stellarium/
    expose:
      - "8090/tcp"
    networks:
      - internal
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        compress: "true"
    volumes:
      - screenshots:/root/screenshots
volumes:
  screenshots:
networks:
  internal: