version: "3"
services:
  #www:
  #  volumes:
  #    - /opt/app/:/opt/app/
  #  ports:
  #    - "3901:3901"
  #  environment:
  #    PGHOST: db
  #    PGUSER: postgres
  #    PGPASSWORD: postgres
  #    PGDATABASE: rp-badges
  #  build:
  #    context: .
  #  networks:
  #    - internal
  #  depends_on:
  #    - "db"
  stellarium:
    build:
      context: ./skybox-stellarium/
      dockerfile: "./Dockerfile"
    networks:
      - internal
    ports:
      - "8090:8090"
networks:
  internal: