version: "3"
services:
  mre:
    volumes:
      - screenshots:/screenshots
    ports:
      - "3901:3901"
    build:
      context: ./skybox-mre/
    environment:
      STEL_URL: http://stellarium:8090
      STEL_OUTDIR: /screenshots/
    networks:
      - internal
    depends_on:
      - "stellarium"
  stellarium:
    build:
      context: ./skybox-stellarium/
    expose:
      - "8090/tcp"
    networks:
      - internal
    volumes:
      - screenshots:/root/screenshots
volumes:
  screenshots:
networks:
  internal: